-- ============================================================================
-- REFERÊNCIA ARQUITETURAL — NÃO APLICADA. NÃO RODAR SEM APROVAÇÃO HUMANA
-- SEPARADA E EXPLÍCITA.
--
-- Este arquivo NÃO está em `supabase/migrations/` deliberadamente, para que
-- `supabase db push`/qualquer automação de migration NUNCA o execute por
-- engano. É documentação executável de uma alternativa avaliada e
-- REJEITADA na Fase 20D — mantida no Git só como referência caso o time
-- decida, no futuro e com decisão humana explícita, trocar de estratégia.
--
-- Contexto (Fase 20D, revisão independente do PR #27 — "API Oficial" em
-- Admin -> Conexões):
--
-- Confirmado por consulta direta ao banco linkado (`supabase db query
-- --linked`) que `public.evolution_instances_meta_cloud`:
--   - tem RLS habilitada, com policies corretas (admin/manager do próprio
--     org OU super_admin, mesma regra em SELECT/INSERT/UPDATE/DELETE);
--   - NÃO tem nenhum GRANT para `authenticated`/`anon` (só `postgres` e
--     `service_role` têm SELECT) — por isso um embed PostgREST feito pelo
--     cliente autenticado falha com `42501 permission denied` assim que
--     existir 1 linha real (hoje 0 linhas em produção).
--
-- Decisão tomada na Fase 20D: NÃO aplicar o GRANT abaixo. Em vez disso, a
-- Edge Function `supabase/functions/instances-api/index.ts` foi estendida
-- (ações `officialApi`/`officialApiAll`) para servir os mesmos dados,
-- sanitizados por allowlist de colunas, autenticando/autorizando no
-- servidor com `service_role` — sem alterar nenhum GRANT real na tabela.
-- Motivo: um GRANT direto amplia a superfície de acesso da tabela a
-- QUALQUER query PostgREST futura do frontend, incluindo um `select('*')`
-- acidental que exporia `access_token_secret_ref` (referência a secret no
-- Vault), `hookcloud_webhook_secret_hash`, `hookcloud_verify_token_hash`
-- e outras colunas nunca destinadas ao cliente.
--
-- Se o time decidir revisitar esta alternativa no futuro, o SQL abaixo é
-- o candidato mínimo (GRANT por COLUNA, nunca a tabela inteira) — mas
-- exigiria, no mínimo: reconfirmar que nenhum `select('*')` foi introduzido
-- em nenhum consumidor frontend desta tabela, e testar cross-tenant e
-- perfil desativado antes de aplicar.
--
-- Confirmado nesta fase: nenhum script deste repositório (`grep -rl
-- "scripts/migration" -- *.sh *.yml *.yaml *.json`) varre ou executa
-- automaticamente arquivos de `scripts/migration/` — mas isso NÃO é uma
-- garantia de segurança por si só, só reduz o risco de execução acidental
-- por automação hoje. A única barreira real é humana.
--
-- NÃO EXECUTAR sem TODOS os passos abaixo, nesta ordem:
--   1. Aprovação humana explícita, vinculada ao hash do commit revisado
--      (nunca a uma versão anterior/posterior deste arquivo).
--   2. Reconfirmação de que a allowlist de colunas abaixo ainda reflete a
--      decisão de segurança (nenhuma coluna de credencial/hash incluída).
--   3. Um humano autorizado COPIA (não move) o SQL revisado para um novo
--      arquivo dentro de `supabase/migrations/`, com timestamp novo — este
--      arquivo em `scripts/migration/` nunca deve ser referenciado
--      diretamente por `supabase db push` (que só processa
--      `supabase/migrations/`); a cópia manual é o próprio ato de decisão,
--      não um detalhe mecânico.
--   4. Só então `supabase db push` roda manualmente por esse humano — nunca
--      por automação/CI, e nunca neste arquivo original.
-- ============================================================================

-- GRANT SELECT (id, evolution_instance_id, organization_id, onboarding_state,
--   onboarding_source, phone_number_id)
--   ON public.evolution_instances_meta_cloud
--   TO authenticated;
--
-- Colunas deliberadamente EXCLUÍDAS do grant (nunca devem sair do backend):
--   access_token_secret_ref, token_expires_at, hookcloud_webhook_secret_hash,
--   hookcloud_webhook_secret_rotated_at, hookcloud_verify_token_hash,
--   hookcloud_verify_token_rotated_at, meta_business_id, waba_id,
--   display_phone_number, quality_rating, messaging_limit_tier,
--   last_error_code, last_error_message, history_sync_status,
--   coexistence_enabled, graph_api_version, created_at, updated_at.
